name: ci-cd

on:
  push:
    branches:
      - master

jobs:
  BUILDS_TESTS_AND_PUSH_TO_DOCKERHUB:
    runs-on: ubuntu-latest
    steps:
      - name: LOGIN TO DOCKER
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: CHECKOUT THE CODE
        uses: actions/checkout@v2
      - name: BUILD THE REACT CLIENT DEV IMAGE FOR TESTING
        run: docker build -f ./client/Dockerfile.dev -t dnyaneshwar89/multi-container-docker-client ./client
      - name: RUN ALL TESTS
        run: docker run -e CI=true dnyaneshwar89/multi-container-docker-client npm run test -- --coverage
      - run: echo "FINISHED BUILDING TEST IMAGE AND RAN ALL TESTS SUCCESSFULLY!."
      - name: BUILD PROD IMAGES
        run: |
          docker build -t dnyaneshwar89/multi-container-docker-client ./client
          docker build -t dnyaneshwar89/multi-container-docker-server ./server
          docker build -t dnyaneshwar89/multi-container-docker-nginx ./nginx
          docker build -t dnyaneshwar89/multi-container-docker-worker ./worker
          echo "BUILT ALL IMAGES SUCCESSFULLY!"
      - name: PUSH TO DOCKERHUB
        run: |
          docker push dnyaneshwar89/multi-container-docker-client
          docker push dnyaneshwar89/multi-container-docker-server 
          docker push dnyaneshwar89/multi-container-docker-nginx 
          docker push dnyaneshwar89/multi-container-docker-worker
